const actionTypes = {
	GET_MOVIE_LIST_REQUEST: "GET_MOVIE_LIST_REQUEST",
	SET_MOVIE_LIST: "SET_MOVIE_LIST",
	GET_MOVIE_SEARCH_REQUEST: "GET_MOVIE_SEARCH_REQUEST",
	SET_SEARCH_KEYWORD: "SET_SEARCH_KEYWORD",
};

export default actionTypes;
